In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from knn import KNNClassifier

In [2]:
iris = load_iris()

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], test_size=0.2)

In [5]:
knn = KNNClassifier()

In [6]:
y_pred = knn.predict(X_train, X_test, y_train)

In [7]:
from sklearn.metrics import classification_report,confusion_matrix

In [8]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         8
          1       0.88      0.64      0.74        11
          2       0.71      0.91      0.80        11

avg / total       0.85      0.83      0.83        30



In [9]:
print(confusion_matrix(y_test, y_pred))

[[ 8  0  0]
 [ 0  7  4]
 [ 0  1 10]]
